### trip basic
GET http://localhost:3000/trip?typeOrigin=stop&nameOrigin=60200913&typeDestination=coord&nameDestination=16.31318:48.21196:WGS84

### trip date time dep
GET http://localhost:3000/trip?typeOrigin=stop&nameOrigin=60200913&typeDestination=coord&nameDestination=16.31318:48.21196:WGS84&date=20211128&time=1000

### trip time arr
GET http://localhost:3000/trip?typeOrigin=stop&nameOrigin=60200913&typeDestination=coord&nameDestination=16.31318:48.21196:WGS84&time=1000&depArr=arrGET http://localhost:3000/trip?typeOrigin=stop&nameOrigin=60200913&typeDestination=coord&nameDestination=16.31318:48.21196:WGS84&time=1000&depArr=arr
### trip route type
GET http://localhost:3000/trip?typeOrigin=stop&nameOrigin=60201015&typeDestination=stop&nameDestination=60200048&routeType=leastinterchange
### trip change speed
GET http://localhost:3000/trip?typeOrigin=stop&nameOrigin=60201015&typeDestination=stop&nameDestination=60200048&changeSpeed=fast
### trip max changes
GET http://localhost:3000/trip?typeOrigin=stop&nameOrigin=60201015&typeDestination=stop&nameDestination=60200048&maxChanges=4